#' PRS_quantitative function
#' This function uses plink2 and outputs Polygenic Risk Scores (PRSs) of all the individuals, using pre-generated GWAS and/or GWEIS summary statistics. Note that the input files used in this function can be generated by using GWAS_quantitative and/or GWEIS_quantitative functions. It is recommended to save the output in a user-specified file (see examples).
#' @param plink_path Path to the PLINK executable application
#' @param b_file Prefix of the binary files, where all .fam, .bed and .bim files have a common prefix
#' @param summary_input Name of the summary statistics file specified by the user 
#' @keywords prs profile scores
#' @export 
#' @importFrom stats binomial fitted.values glm lm
#' @importFrom utils read.table 
#' @return This function will output
#' \item{Q_trd.sscore}{PRSs for each individual}
#' @examples \dontrun{ 
#' x <- PRS_quantitative(plink_path, DummyData, summary_input = "Q_out.trd.sum")
#' sink("Q_trd.sscore") #to create a file in the working directory
#' write.table(x, sep = " ", row.names = FALSE, quote = FALSE) #to write the output
#' sink() #to save the output
#' head(x) #to read the head of all columns in the output
#' x$V1 #to extract the family ID's of target dataset (FID)
#' x$V2 #to extract the individual ID's of target dataset (IID)
#' x$V3 #to extract the number of alleles across scored variants (ALLELE_CT)
#' x$V4 #to extract the sum of named allele dosages (NAMED_ALLELE_DOSAGE_SUM)
#' x$V5 #to extract the polygenic risk scores (SCORE1_AVG)
#' y <- PRS_quantitative(plink_path, DummyData, summary_input = "Q_out.add.sum")
#' sink("Q_add.sscore") #to create a file in the working directory
#' write.table(y, sep = " ", row.names = FALSE, quote = FALSE) #to write the output
#' sink() #to save the output
#' z <- PRS_quantitative(plink_path, DummyData, summary_input = "Q_out.gxe.sum")
#' sink("Q_gxe.sscore") #to create a file in the working directory
#' write.table(z, sep = " ", row.names = FALSE, quote = FALSE) #to write the output
#' sink() #to save the output
#' }
PRS_quantitative <- function(plink_path, b_file, summary_input){               
  runPLINK <- function(PLINKoptions = "") system(paste(plink_path, PLINKoptions))
    log_file <- runPLINK(paste0(" --bfile ", b_file, 
                    " --score ", noquote(summary_input), " 3 6 9 header --out ", tempdir(),"/prs"))
    out = read.table(paste0(tempdir(), "/prs.sscore"), header = F)
  return(out)
}