#' summary_regular_binary function
#' This function outputs the summary of regular model and final risk score values of each individual in the target dataset using pre-generated Polygenic Risk Scores (PRSs) of all the individuals. Note that the input used in this function can be generated by using PRS_binary function.
#' @param Bphe_target Phenotype file containing family ID, individual ID and phenotype of the target dataset as columns, without heading
#' @param Bcov_target Covariate file containing family ID, individual ID, standardized covariate, square of standardized covariate, and/or confounders of the target dataset as columns, without heading
#' @param trd_score PRSs generated using additive SNP effects of GWAS summary statistics
#' @param add_score PRSs generated using additive SNP effects of GWEIS summary statistics
#' @param gxe_score PRSs generated using interaction SNP effects of GWEIS summary statistics
#' @param Model Specify the model number (1: y = PRS_trd + E + PRS_trd x E + confounders, 2: y = PRS_add + E + PRS_add x E + confounders, 3: y = PRS_add + E + PRS_gxe x E + confounders, 4: y = PRS_add + E + PRS_gxe + PRS_gxe x E + confounders, 5: y = PRS_add + E + E^2 + PRS_gxe + PRS_gxe x E + confounders, where y is the outcome variable, E is the covariate of interest, PRS_trd and PRS_add are the polygenic risk scores computed using additive SNP effects of GWAS and GWEIS summary statistics respectively, and PRS_gxe is the polygenic risk scores computed using GxE interaction SNP effects of GWEIS summary statistics.)
#' @keywords regression summary risk scores
#' @export 
#' @importFrom stats binomial fitted.values glm lm
#' @importFrom utils read.table write.table
#' @return This function will output
#' \item{Bsummary.txt}{the summary of the fitted model}
#' \item{Individual_risk_values.txt}{the estimated risk values of individuals in the target sample}
#' @examples \dontrun{ 
#' a <- GWAS_binary(plink_path, DummyData, Bphe_discovery, Bcov_discovery)
#' b <- GWEIS_binary(plink_path, DummyData, Bphe_discovery, Bcov_discovery)
#' p <- PRS_binary(plink_path, DummyData, summary_input = a)
#' q <- PRS_binary(plink_path, DummyData, summary_input = b[[1]])
#' r <- PRS_binary(plink_path, DummyData, summary_input = b[[2]])
#' summary_regular_binary(Bphe_target, Bcov_target, 
#'                             trd_score = p,
#'                             Model = 1)
#' summary_regular_binary(Bphe_target, Bcov_target, 
#'                             add_score = q,
#'                             Model = 2)
#' summary_regular_binary(Bphe_target, Bcov_target, 
#'                             add_score = q, 
#'                             gxe_score = r, 
#'                             Model = 3) 
#' summary_regular_binary(Bphe_target, Bcov_target, 
#'                             add_score = q, 
#'                             gxe_score = r, 
#'                             Model = 4) 
#' x <- summary_regular_binary(Bphe_target, Bcov_target, 
#'                             add_score = q, 
#'                             gxe_score = r, 
#'                             Model = 5) 
#' sink("Bsummary.txt") #to create a file in the working directory
#' print(x[[1]][[1]]) #to write the output
#' sink() #to save the output
#' sink("Individual_risk_values.txt") #to create a file in the working directory
#' write.table(x[[2]], sep = " ", row.names = FALSE, col.names = FALSE, 
#' quote = FALSE) #to write the output
#' sink() #to save the output
#' x[[1]][[1]] #to obtain the model summary output
#' x[[1]][[2]] #to extract "Call" of the model summary
#' x[[1]][[3]] #to extract terms of the model summary
#' x[[1]][[4]] #to extract family information of the model summary
#' x[[1]][[5]] #to extract deviance information of the model summary
#' x[[1]][[6]] #to extract AIC information of the model summary
#' x[[1]][[7]] #to extract contrasts of the model summary
#' x[[1]][[8]] #to extract degrees of freedom (df) of residuals of 
#'             #the model summary
#' x[[1]][[9]] #to extract "Null deviance" of the model summary
#' x[[1]][[10]] #to extract degrees of freedom (df) of null deviance 
#'              #of the model summary
#' x[[1]][[11]] #to extract "iter" of the model summary
#' x[[1]][[12]] #to extract deviance residuals 
#' x[[1]][[13]] #to extract regrerssion coefficients of the model summary
#' x[[1]][[14]] #to extract aliesed information of the model summary
#' x[[1]][[15]] #to extract dispersion information of the model summary
#' x[[1]][[16]] #to extract degrees of freedom of the model summary
#' x[[1]][[17]] #to extract unscaled variance covariance matrix of all variables
#' x[[1]][[18]] #to extract scaled variance covariance matrix of all variables
#' head(x[[2]]) #to view the head of the predicted risk values of target individuals
#' x[[2]][,1] #to extract the column containing family ID's  
#' x[[2]][,2] #to extract the column containing individual ID's
#' x[[2]][,3] #to extract the column containing predicted risk scores 
#' }
summary_regular_binary <- function(Bphe_target, Bcov_target, trd_score = NULL, add_score = NULL, gxe_score = NULL, Model){
  cov_file <- read.table(Bcov_target)
  n_confounders = ncol(cov_file) - 4
  fam=read.table(Bphe_target, header=F) 
  colnames(fam) <- c("FID", "IID", "PHENOTYPE")
  dat=read.table(Bcov_target, header=F)
  colnames(dat)[1] <- "FID"
  colnames(dat)[2] <- "IID"
  if(!is.null(trd_score)){
    sink(paste0(tempdir(), "/trd_score"))
    write.table(trd_score, sep = " ", row.names = FALSE, quote = FALSE)
    sink()
    prs0_all=read.table(paste0(tempdir(), "/trd_score"), header=T)
    colnames(prs0_all)[1] <- "FID"
    colnames(prs0_all)[2] <- "IID"
    prs0=merge(fam, prs0_all, by = "FID")
    m1 <- match(dat$IID, prs0$IID.x)     
    ps0=scale(prs0$V5)
    out = fam$PHENOTYPE[m1]
    cov=scale(dat$V3[m1])
    xv0=scale(prs0$V5*cov)
    cov2=scale(cov^2)
  }
  if(!is.null(add_score)){
    sink(paste0(tempdir(), "/add_score"))
    write.table(add_score, sep = " ", row.names = FALSE, quote = FALSE)
    sink()
    prs1_all=read.table(paste0(tempdir(), "/add_score"), header=T)
    colnames(prs1_all)[1] <- "FID"
    colnames(prs1_all)[2] <- "IID"
    prs1=merge(fam, prs1_all, by = "FID")
    m1 <- match(dat$IID, prs1$IID.x)
    ps1=scale(prs1$V5)
    out = fam$PHENOTYPE[m1]
    cov=scale(dat$V3[m1])
    xv1=scale(prs1$V5*cov)
    cov2=scale(cov^2)
  }
  if(!is.null(gxe_score)){
    sink(paste0(tempdir(), "/gxe_score"))
    write.table(gxe_score, sep = " ", row.names = FALSE, quote = FALSE)
    sink()
    prs2_all=read.table(paste0(tempdir(), "/gxe_score"), header=T)
    colnames(prs2_all)[1] <- "FID"
    colnames(prs2_all)[2] <- "IID"
    prs2=merge(fam, prs2_all, by = "FID")
    m1 <- match(dat$IID, prs2$IID.x)
    ps2=scale(prs2$V5)
    out = fam$PHENOTYPE[m1]
    cov=scale(dat$V3[m1])
    xv2=scale(prs2$V5*cov)
    cov2=scale(cov^2)
  }
  if(Model == 1){
    if(n_confounders == 0){
      df_new <- as.data.frame(cbind(out, cov, ps0, xv0))
      colnames(df_new)[1] <- "out"
      colnames(df_new)[2] <- "E"
      colnames(df_new)[3] <- "PRS_trd"
      colnames(df_new)[4] <- "PRS_trd x E"
      m = glm(out ~., data = df_new, family = binomial(link = logit))
      m_fit <- fitted.values(m)
    }else{
      conf_var <- matrix(ncol = n_confounders, nrow = nrow(dat))
      for (k in 1:n_confounders) {
        conf_var[, k] <- as.numeric(dat[, k+4])
      }
      conf_var <- conf_var[m1,]
      df_new <- as.data.frame(cbind(out, cov, ps0, xv0, conf_var))
      colnames(df_new)[1] <- "out"
      colnames(df_new)[2] <- "E"
      colnames(df_new)[3] <- "PRS_trd"
      colnames(df_new)[4] <- "PRS_trd x E"
      m = glm(out ~., data = df_new, family = binomial(link = logit))
      m_fit <- fitted.values(m)
    }
    s <- summary(m)
    out1 <- list(s, s$call, s$terms, s$family, s$deviance, s$aic, s$contrasts, 
                 s$df.residual, s$null.deviance, s$df.null, s$iter, s$deviance.resid, 
                 s$coefficients, s$aliesed, s$dispersion, s$df, s$cov.unscaled, s$cov.scaled)
    out2 <- cbind(fam$FID[m1], fam$IID[m1], m_fit)
    out_all <- list(out1, out2)
  }
  if(Model == 2){
    if(n_confounders == 0){
      df_new <- as.data.frame(cbind(out, cov, ps1, xv1))
      colnames(df_new)[1] <- "out"
      colnames(df_new)[2] <- "E"
      colnames(df_new)[3] <- "PRS_add"
      colnames(df_new)[4] <- "PRS_add x E"
      m = glm(out ~., data = df_new, family = binomial(link = logit))
      m_fit <- fitted.values(m)
    }else{
      conf_var <- matrix(ncol = n_confounders, nrow = nrow(dat))
      for (k in 1:n_confounders) {
        conf_var[, k] <- as.numeric(dat[, k+4])
      }
      conf_var <- conf_var[m1,]
      df_new <- as.data.frame(cbind(out, cov, ps1, xv1, conf_var))
      colnames(df_new)[1] <- "out"
      colnames(df_new)[2] <- "E"
      colnames(df_new)[3] <- "PRS_add"
      colnames(df_new)[4] <- "PRS_add x E"
      m = glm(out ~., data = df_new, family = binomial(link = logit))
      m_fit <- fitted.values(m)
    }
    s <- summary(m)
    out1 <- list(s, s$call, s$terms, s$family, s$deviance, s$aic, s$contrasts, 
                 s$df.residual, s$null.deviance, s$df.null, s$iter, s$deviance.resid, 
                 s$coefficients, s$aliesed, s$dispersion, s$df, s$cov.unscaled, s$cov.scaled)
    out2 <- cbind(fam$FID[m1], fam$IID[m1], m_fit)
    out_all <- list(out1, out2)
  }
  if(Model == 3){
    if(n_confounders == 0){
      df_new <- as.data.frame(cbind(out, cov, ps1, xv2))
      colnames(df_new)[1] <- "out"
      colnames(df_new)[2] <- "E"
      colnames(df_new)[3] <- "PRS_add"
      colnames(df_new)[4] <- "PRS_gxe x E"
      m = glm(out ~., data = df_new, family = binomial(link = logit))
      m_fit <- fitted.values(m)
    }else{
      conf_var <- matrix(ncol = n_confounders, nrow = nrow(dat))
      for (k in 1:n_confounders) {
        conf_var[, k] <- as.numeric(dat[, k+4])
      }
      conf_var <- conf_var[m1,]
      df_new <- as.data.frame(cbind(out, cov, ps1, xv2, conf_var))
      colnames(df_new)[1] <- "out"
      colnames(df_new)[2] <- "E"
      colnames(df_new)[3] <- "PRS_add"
      colnames(df_new)[4] <- "PRS_gxe x E"
      m = glm(out ~., data = df_new, family = binomial(link = logit))
      m_fit <- fitted.values(m)
    }
    s <- summary(m)
    out1 <- list(s, s$call, s$terms, s$family, s$deviance, s$aic, s$contrasts, 
                 s$df.residual, s$null.deviance, s$df.null, s$iter, s$deviance.resid, 
                 s$coefficients, s$aliesed, s$dispersion, s$df, s$cov.unscaled, s$cov.scaled)
    out2 <- cbind(fam$FID[m1], fam$IID[m1], m_fit)
    out_all <- list(out1, out2)
  }
  if(Model == 4){
    if(n_confounders == 0){
      df_new <- as.data.frame(cbind(out, cov, ps1, ps2, xv2))
      colnames(df_new)[1] <- "out"
      colnames(df_new)[2] <- "E"
      colnames(df_new)[3] <- "PRS_add"
      colnames(df_new)[4] <- "PRS_gxe"
      colnames(df_new)[5] <- "PRS_gxe x E"
      m = glm(out ~., data = df_new, family = binomial(link = logit))
      m_fit <- fitted.values(m)
    }else{
      conf_var <- matrix(ncol = n_confounders, nrow = nrow(dat))
      for (k in 1:n_confounders) {
        conf_var[, k] <- as.numeric(dat[, k+4])
      }
      conf_var <- conf_var[m1,]
      df_new <- as.data.frame(cbind(out, cov, ps1, ps2, xv2, conf_var))
      colnames(df_new)[1] <- "out"
      colnames(df_new)[2] <- "E"
      colnames(df_new)[3] <- "PRS_add"
      colnames(df_new)[4] <- "PRS_gxe"
      colnames(df_new)[5] <- "PRS_gxe x E"
      m = glm(out ~., data = df_new, family = binomial(link = logit))
      m_fit <- fitted.values(m)
    }
    s <- summary(m)
    out1 <- list(s, s$call, s$terms, s$family, s$deviance, s$aic, s$contrasts, 
                 s$df.residual, s$null.deviance, s$df.null, s$iter, s$deviance.resid, 
                 s$coefficients, s$aliesed, s$dispersion, s$df, s$cov.unscaled, s$cov.scaled)
    out2 <- cbind(fam$FID[m1], fam$IID[m1], m_fit)
    out_all <- list(out1, out2)
  }
  if(Model == 5){
    if(n_confounders == 0){
      df_new <- as.data.frame(cbind(out, cov, cov2, ps1, ps2, xv2))
      colnames(df_new)[1] <- "out"
      colnames(df_new)[2] <- "E"
      colnames(df_new)[3] <- "E squared"
      colnames(df_new)[4] <- "PRS_add"
      colnames(df_new)[5] <- "PRS_gxe"
      colnames(df_new)[6] <- "PRS_gxe x E"
      m = glm(out ~., data = df_new, family = binomial(link = logit))
      m_fit <- fitted.values(m)
    }else{
      conf_var <- matrix(ncol = n_confounders, nrow = nrow(dat))
      for (k in 1:n_confounders) {
        conf_var[, k] <- as.numeric(dat[, k+4])
      }
      conf_var <- conf_var[m1,]
      df_new <- as.data.frame(cbind(out, cov, cov2, ps1, ps2, xv2, conf_var))
      colnames(df_new)[1] <- "out"
      colnames(df_new)[2] <- "E"
      colnames(df_new)[3] <- "E squared"
      colnames(df_new)[4] <- "PRS_add"
      colnames(df_new)[5] <- "PRS_gxe"
      colnames(df_new)[6] <- "PRS_gxe x E"
      m = glm(out ~., data = df_new, family = binomial(link = logit))
      m_fit <- fitted.values(m)
    }
    s <- summary(m)
    out1 <- list(s, s$call, s$terms, s$family, s$deviance, s$aic, s$contrasts, 
                 s$df.residual, s$null.deviance, s$df.null, s$iter, s$deviance.resid, 
                 s$coefficients, s$aliesed, s$dispersion, s$df, s$cov.unscaled, s$cov.scaled)
    out2 <- cbind(fam$FID[m1], fam$IID[m1], m_fit)
    out_all <- list(out1, out2)
  }
  return(out_all)
}
